### ISSUE TITLE
extending hideOn

### ISSUE THREAD

**Issue by McFarts** [darsain/tooltips#12]
Hello,

I'm using this great tooltip system for a simple menu, I am running into a problem.

I have created a custom tooltip instance like so:

```
mmenu = new Tooltips(qs('.Menu'), {
	key: 'menu',
	showOn: 'mouseenter',
	hideOn: 'mouseleave'
});
```
HTML:

```
<div class="Menu conr">
			<div class="m" data-menu="<a href=#>Profile Settings</a>" data-menu-place="bottom"> <div> <span class="sprite na"></span> Monkey </div> </div>
			
		</div>

```

Which works as expected. But, if a user wants to click anywhere on the menu they cannot because it disappears. This is because the hideOn property handler is pertinent to the element itself and not the menu itself. 

Is it possible to have it so the menu only disappears when moving your mouse out side of the tooltip menu, not the tooltip element that the tooltip is spawned from?

A Gif I made:
http://i.gyazo.com/14c508a26d79aa9dbec384bd0f897f36.gif

**Comment by darsain** [comment]
Tooltips right now doesn't have a logic for supporting interactive tooltips. It just displays/hides tooltips on elements.

Interactive tooltips support is planned for 1.0, but I can't give you any ETA.

Meanwhile, if you really need this, you can just consume the underlying [darsain/tooltip](https://github.com/darsain/tooltip) library, and implement showing hiding logic based on what you need to happen.

Closing in favor of #6.
