### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by adam-lynch** [darsain/tooltips#7]
It would be good if we could install via bower. You just need a simple `bower.json` at the root.

**Comment by adam-lynch** [comment]
Also, you need to add the dependencies (`event`, etc) in the bower.json. Right now it's not even possible to use this with bower by installing from GitHub (this repo).

**Comment by darsain** [comment]
Tooltips dependencies couldn't be resolved by bower. I'd have to build a standalone version with UMD transports, and place it in a `dist` directory inside the repository, which is a practice I hate with passion. It introduces dependency inlining and inefficient builds for everyone using it.

There will always be standalone builds available, mostly because they're useful for replicating issues on jsfiddle and similar services, but I don't plan registering to bower. I've actually had a few libs there, and I decided to remove them. Bower is a bad practice. Better than manual installs into global variables, but still bad.

I would reconsider if supporting bower would be mostly effortless while not polluting the main branch, but I don't think that's possible.

**Comment by adam-lynch** [comment]
I don't think you necessarily have to inline all dependencies into a compiled version of your script. There are plenty of stuff on Bower which just work if you have jQuery as a global for example and then of course you can have UMD but you're against UMD? I'm not sure exactly what you mean by UMD transports.

---

Could you clarify how you someone should consume this without `component`?

---

> I would reconsider if supporting bower would be mostly effortless while not polluting the main branch, but I don't think that's possible.

Fair enough, some projects end up with a second repo just for bower. But then again, I don't see the problem with a `dist` directory and a simple `gulpfile` or something.

**Comment by darsain** [comment]
>  I'm not sure exactly what you mean by UMD transports.

Universal Module Definition, i.e. starting all your files like this: http://pastie.org/9861906

> Could you clarify how you someone should consume this without component?

[duo](https://github.com/duojs/duo), [component](https://github.com/componentjs/component), and manual installs of pre-build files is currently the only way how to consume my libs.

---

I'm trying to make my open source work as painless as possible. The front-end world is already too frustrating and burn-out inducing, and I don't want to make it even worse by intentionally producing sub-optimal ugly code full of hacks and quirks just so it can be consumed by all package managers.

You can basically label me as a guy that makes libraries for himself. And if you happen to come to the same conclusion of which tools are currently the best for the job as me, awesome. If not, you should look for an alternative that has been written with bower or your package manager of choice in mind.

Sorry about that. Until ES6 modules take hold I don't see this situation getting better.

**Comment by adam-lynch** [comment]
Ok, I know UMD, just never saw anyone write "UMD transports". I don't see the problem if it makes things more accessible, especially when the adding of that stuff can be automated.

> duo, component, and manual installs of pre-build files is currently the only way how to consume my libs.

Ok.

> You can basically label me as a guy that makes libraries for himself. And if you happen to come to the same conclusion of which tools are currently the best for the job as me, awesome. If not, you should look for an alternative that has been written with bower or your package manager of choice in mind.

Fair enough. I guess I'll be sticking to Tooltipster for now. I've seen Duo before and it looks interesting for sure (something I'll probably end up switching to) but I've ongoing projects with multiple different setups going on which this wouldn't work for. For some projects, we have an intentionally very simple /  dumb setup (like [this](http://engineroom.teamwork.com/hassle-free-third-party-dependencies/)) where we keep versions of dependencies under strict control.
