### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by adam-lynch** [darsain/tooltips#8]
There hasn't been any commits in a long time.

**Comment by darsain** [comment]
I've been busy. And there are still things on the underlying tooltip library that need to be done before I start on this one again.

That being said, things I want to do to this are only a few new features and a code prettifying. There are no known issues, so why exactly do you require commits?

**Comment by adam-lynch** [comment]
I don't need commits. It's just usually a warning sign if something hasn't any been worked on in awhile and doesn't have a lot of stars. Just an enquiry. 

I've ended up using [Tooltipster](http://iamceege.github.io/tooltipster/) for now because it fits in with my use case better (with bower and [main-bower-files](https://github.com/ck86/main-bower-files)). Related: #7
