### ISSUE TITLE
Re displaying the tooltip without mouse hover. [Fixed]

### ISSUE THREAD

**Issue by Dillybob92** [darsain/tooltips#9]
For example:
http://i.gyazo.com/b60c3d4d23b62b11fdeeeffad3d91a70.png

This is a scroll of Wisdom. It's indentfying an item and using ajax to change the data-tooltip attribute dynamically. I then call:

tips.reload() to refresh that specific item's tooltip. The problem is, the tooltip just disappears ( http://i.gyazo.com/547c7b85125f600ecd75847f19b3636a.png ) until you mouse over it again (the new tooltip data is applied and works!), but the issue is, I don't want to mouse over it again.

**Is it possible to just simply refresh the tooltips (fade in / out) upon tips.reload() instead of hiding it and having the user mouse over it again to show it's new contents?**

Thanks Darsain if you can help!

**Comment by Dillybob92** [comment]
WOW!!! Epic.

`tips.toggle(qs('[item_id="{$itemid}"]'));`

Boom. The tips.toggle function is a Godsend! Awesome! :)

**Comment by darsain** [comment]
the `#reload()` function destroys all tooltip instances, unbinds all events, and than selects the elements with `[data-{key}]` attribute and recreates the tooltips on them.

**Tooltips** (this library) is just a comfy wrapper over **Tooltip** library for simple hover functionality. If you want more control, grab the underlying **Tooltip** library, and implement the show/hide/content handling yourself.
